site_name: SeaSearch Manual
site_author: seafile
docs_dir: ./manual
site_url: https://haiwen.github.io/seasearch-docs/

repo_name: seacloud-lab/seasearch-docs
repo_url: https://github.com/seacloud-lab/seasearch-docs/
edit_uri: blob/master/manual

copyright: Copyright &copy; 2026 Seacloud labs.

theme:
  name: material
  logo: media/seafile-transparent-1024.png
  favicon: media/favicon.ico
  features:
    - navigation.footer
    - navigation.tracking
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - math
    - content.code.copy
    - content.code.annotate

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - awesome-pages
  - mike

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/seacloud-lab/seasearch-docs/
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
      toc_depth: "1-4"
  - pymdownx.tabbed: 
      alternate_style: true
  - pymdownx.superfences: # allows 1) nesting of fences 2) custom fences 3) disable indented code
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

# Page tree
nav:
  - Introduction: README.md
  - Deployment and Usage:
    - Overview: usage/overview.md
    - Deployment:
      - Single node: usage/deploy_single_node.md
      - Cluster: usage/deploy_cluster.md
    - Usage and management:
      - Use and access SeaSearch APIs: usage/use_and_access_seasearch_apis.md
      - Backup and Restore: usage/backup_and_restore.md
  - Configuration:
    - Overview: config/README.md
    - Example: config/example.md
  - SeaSearch API:
    - Overview: api/overview.md
    - API Authentication: api/authentication.md
    - Index management: api/index_management.md
    - Document operations: api/document_operation.md
    - Search document: api/search_document.md
    - Vector search:
      - Vector search API: api/vector_search_api.md
      - Vector search example: api/vector_search_example.md
  - ChangeLog:
    - SeaSearch server: changelog/seasearch_server.md
